### PR TITLE
Fix some issues reported by lintian

### PR DESCRIPTION
**Pull request by debian-janitor**
Fix some issues reported by lintian
* Bump debhelper from old 11 to 12. ([package-uses-old-debhelper-compat-version](https://lintian.debian.org/tags/package-uses-old-debhelper-compat-version.html))
* Set debhelper-compat version in Build-Depends. ([uses-debhelper-compat-file](https://lintian.debian.org/tags/uses-debhelper-compat-file.html))

This merge proposal was created automatically by the [Janitor bot](https://janitor.debian.net/lintian-fixes).

You can follow up to this merge proposal as you normally would.

Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/dte/77e2fb3b-6439-4a3b-b763-a542c8c8581b.

These changes have no impact on the [binary debdiff](
https://janitor.debian.net/api/run/77e2fb3b-6439-4a3b-b763-a542c8c8581b/debdiff?filter_boring=1).

You can also view the [diffoscope diff](https://janitor.debian.net/api/run/77e2fb3b-6439-4a3b-b763-a542c8c8581b/diffoscope?filter_boring=1) ([unfiltered](https://janitor.debian.net/api/run/77e2fb3b-6439-4a3b-b763-a542c8c8581b/diffoscope)).

### CODE REVIEW

**Comment by exaexa** [comment]
Hi,
I didn't have time to do a proper repack&upload yet, I'll do it asap.

**Comment by craigbarnes** [comment]
Ah ok. No worries. Just thought perhaps it had slipped your mind.

**Comment by exaexa** [comment]
Uploaded at https://mentors.debian.net/package/dte/  will look for sponsor

**Comment by exaexa** [comment]
OK cool, seems uploaded. :]

**Comment by craigbarnes** [comment]
Cool. That seems to have fixed most of the warnings.

FWIW, I think the remaining `compiler-flags-hidden` warnings are caused by not setting `V=1` for `make check`. I'm going to release 1.10 pretty soon though, so it probably makes sense to combine that with the next version bump commit.

**Pull request merged**
